name: Build ChimeraOS Mesa

on:
  push:
    branches: [ main ]
    tags: '*'
  workflow_dispatch:

env:
  PKGDEST: "/tmp/mesa-chimeraos"
  BUILDDIR: "/tmp/build"

jobs:
  build-mesa:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        package: [mesa, lib32-mesa]

    outputs:
      full_version: ${{ steps.set-mesa-version.outputs.full_version }}

    container: archlinux:base-devel

    steps:
      - uses: actions/checkout@v3
      - name: Create build user
        run: |
          useradd -m build
          cp -vR ${{ matrix.package }} /home/build/${{ matrix.package }}
          chown -vR build /home/build/${{ matrix.package }}
      - name: Set up pacman keyring
        run: |
          pacman-key --init
          pacman-key --populate archlinux
          mkdir -p /etc/gnupg && echo "auto-key-retrieve" >> /etc/gnupg/gpg.conf
          echo -e "[multilib]\nInclude = /etc/pacman.d/mirrorlist\n" >> /etc/pacman.conf
      - name: Generate .SRCINFO
        run: |
          ls -ahl /home/build/${{ matrix.package }}
          su build bash -c "cd /home/build/${{ matrix.package }} && makepkg --printsrcinfo > /home/build/${{ matrix.package }}/.SRCINFO"
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm $(sed -n -e 's/^[[:space:]]*\(make\)\?depends\(_x86_64\)\? = \([[:alnum:][:punct:]]*\)[[:space:]]*$/\3/p' /home/build/${{ matrix.package }}/.SRCINFO)
      - name: Build mesa-chimeraos package
        id: build-mesa-package
        shell: bash
        run: |
          su build bash -c "cd /home/build/${{ matrix.package }}  && MAKEFLAGS=-j$(nproc) makepkg"
      - if: matrix.package == 'mesa'
        name: Set mesa package version
        id: set-mesa-version
        shell: bash
        run: |
          . /home/build/${{ matrix.package }}/PKGBUILD
          full_version=${pkgver}-${pkgrel}
          echo "full_version=$full_version" >> "$GITHUB_OUTPUT"
      - name: Upload package artifact
        uses: actions/upload-artifact@v3
        with:
          name: mesa-chimeraos-${{matrix.package}}
          path: |
            ${{ env.PKGDEST }}/*.pkg.tar.zst
          if-no-files-found: error

  make-release:
    if: |
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')) ||
      (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    needs: [build-mesa]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: mesa-chimeraos-mesa
          path: ${{ env.PKGDEST }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: mesa-chimeraos-lib32-mesa
          path: ${{ env.PKGDEST }}

      - name: Make release
        uses: softprops/action-gh-release@v1
        with:
          name: mesa-chimeraos-${{needs.build-mesa.outputs.full_version}}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ${{ env.PKGDEST }}/*.pkg.tar.zst
